server:
  port: 7000
spring:
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.115.55.123:3306/gulimall_sms
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto